// This is not used... Yet -> import jobImage from './images/job-image.jpg';

export const availableJobs = [
  { id: 1, company: 'Tech Innovators', position: 'Frontend Developer' },
  { id: 2, company: 'Data Wizards', position: 'Data Scientist' },
  { id: 3, company: 'Cloud Creators', position: 'Cloud Solutions Architect' },
  { id: 4, company: 'Cyber Guardians', position: 'Cybersecurity Analyst' },
  { id: 5, company: 'Mobile Maestros', position: 'Mobile App Developer' },
  { id: 6, company: 'AI Pioneers', position: 'AI/ML Engineer' },
  { id: 7, company: 'Code Crafters', position: 'Software Engineer' },
  { id: 8, company: 'E-commerce Experts', position: 'E-commerce Developer' },
  { id: 9, company: 'Network Navigators', position: 'Network Engineer' },
  { id: 10, company: 'UX/UI Gurus', position: 'UX/UI Designer' },
  { id: 11, company: 'Game Developers Ltd.', position: 'Game Developer' },
  { id: 12, company: 'Blockchain Builders', position: 'Blockchain Developer' },
  { id: 13, company: 'DevOps Dynamos', position: 'DevOps Engineer' },
  { id: 14, company: 'Tech Support Pros', position: 'Technical Support Specialist' },
  { id: 15, company: 'Database Masters', position: 'Database Administrator' },
  { id: 16, company: 'IT Consultants Inc.', position: 'IT Consultant' },
  { id: 17, company: 'Automation Alchemists', position: 'Automation Engineer' },
  { id: 18, company: 'Digital Designers Co.', position: 'Digital Designer' },
  { id: 19, company: 'Quality Assurance Experts', position: 'QA Tester' },
  { id: 20, company: 'System Architects', position: 'System Architect' },
  { id: 21, company: 'Web Design Wizards', position: 'Web Designer' },
  { id: 22, company: 'Embedded Systems Innovators', position: 'Embedded Systems Engineer' },
  { id: 23, company: 'HealthTech Innovations', position: 'HealthTech Developer' },
  { id: 24, company: 'Augmented Reality Creators', position: 'AR Developer' },
  { id: 25, company: 'Big Data Analysts', position: 'Big Data Analyst' },
  { id: 26, company: 'UI Framework Developers', position: 'UI Framework Engineer' },
  { id: 27, company: 'Digital Marketing Experts', position: 'Digital Marketing Specialist' },
  { id: 28, company: 'Cloud Infrastructure Engineers', position: 'Cloud Infrastructure Engineer' },
  { id: 29, company: 'AI Ethics Specialists', position: 'AI Ethics Analyst' },
  { id: 30, company: 'Quantum Computing Enthusiasts', position: 'Quantum Computing Developer' },
];
